//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITP244_Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderPart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesOrderPart()
        {
            this.ShipmentParts = new HashSet<ShipmentPart>();
        }
    
        public int SalesOrderPartId { get; set; }
        public int SalesOrderNumber { get; set; }
        public int PartId { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
    
        public virtual Part Part { get; set; }
        public virtual SalesOrder SalesOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipmentPart> ShipmentParts { get; set; }
    }
}
