//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITP244_Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spoilage
    {
        public int SpoilageID { get; set; }
        public System.DateTime SpoilageDate { get; set; }
        public int PartID { get; set; }
        public int Quantity { get; set; }
        public decimal UnitCost { get; set; }
    
        public virtual Part Part { get; set; }
    }
}
